#!/bin/bash -x

flist=$1
start=$2
end=$3
inputxml=$4
gearxml=$5
isolep=$6
model=$7

outputDir=/hsm/ilc/users/yokugawa/preset_N_run/${model}/${isolep}
logDir=./log

tmpxmlDir=./tmpxml
xmlDir=./myxml

for count in $(seq $start $end)
  do
  input=`head -${count} ${flist} | tail -1`
  echo ${input}
  filename=`basename ${input}`
  filename="${filename%.*}"
  echo ${filename}
  tmpxml=${tmpxmlDir}/${filename}.xml
  lastxml=${xmlDir}/${filename}.xml
  
  log=${logDir}/${filename}.log 
	rootfile=${outputDir}/QQbarProcessor_out/${filename}.root

  sed -e "/<!-- INPUT.slcio -->/i $input" $inputxml | sed -e "/<!-- GEAR.xml -->/i $gearxml" | sed -e "/<!-- OUTPUT.root -->/i $rootfile" > $lastxml

  ${MARLIN}/bin/Marlin $lastxml > $log 2>&1
  
  echo "$count event finished"
  
done

