#!/bin/sh

data_input=$1
nfirst=$2
nlast=$3
nrun=$4
inputxml=$5
gearxml=$6
isolep=$7
model=$8

flist=list/${isolep}_${model}.list
if [ ! -f ${flist} ] ; then
    `find ${data_input} -name *.slcio | sort > ${flist}`
else
	rm -rf ${flist}
    `find ${data_input} -name *.slcio | sort > ${flist}`
fi

nf=`more ${flist} | wc -l`
echo "number of files for process: " ${nf}

if [ ${nlast} -le 0 ] || [ ${nlast} -ge ${nf} ] ; then
    nlast=${nf}
fi

njobs=$[($nlast-$nfirst)/$nrun+1]
seqlist=`seq 1 $njobs`
for seq in $seqlist; do
    nrun0=$[$nfirst+$nrun*($seq-1)]
    nrun1tmp=$[$nrun0+$nrun-1]
    if [ $nrun1tmp -le $nlast ] ; then
	nrun1=$nrun1tmp
    else
	nrun1=$nlast
    fi
    echo ${isolep} ${model} $nrun0 $nrun1 $nrun $njobs
    log=./sublog/${isolep}"_"${model}"_"`printf %03d $seq`.log
    bsub -q s -J "ana"`printf %03d $seq` -o $log "./runMarlin2 ${flist} $nrun0 $nrun1 $inputxml $gearxml $isolep $model"
#    ./runMarlin2 ${flist} $nrun0 $nrun1 $inputxml
#    sleep 5
done
